-- Add high school and sports questions to complete the question database

-- Insert challenging questions for "Srednja šola" category (High School) - 100 questions
INSERT INTO public.questions (question_text, subject, option_a, option_b, option_c, option_d, correct_answer, grade_level, difficulty_order, category) VALUES
-- Advanced Math Questions
('Koliko je integral ∫x² dx?', 'Matematika', 'x³/3 + C', 'x³ + C', '2x + C', 'x³/2 + C', 'A', 11, 1, 'Srednja šola'),
('Katera je derivacija funkcije f(x) = e^x?', 'Matematika', 'e^x', 'xe^(x-1)', 'e^(x+1)', 'x·e^x', 'A', 12, 2, 'Srednja šola'),
('Koliko je lim(x→0) (sin x)/x?', 'Matematika', '0', '1', '∞', 'Ne obstaja', 'B', 12, 3, 'Srednja šola'),
('Katera je enačba premice, ki gre skozi točki A(1,2) in B(3,6)?', 'Matematika', 'y = 2x', 'y = 2x + 1', 'y = x + 1', 'y = 3x - 1', 'A', 11, 4, 'Srednja šola'),
('Koliko je determinanta matrike [[2,3],[1,4]]?', 'Matematika', '5', '8', '11', '7', 'A', 12, 5, 'Srednja šola'),

-- Advanced Physics
('Katera je enačba za kinetično energijo?', 'Fizika', 'E = mc²', 'E = ½mv²', 'E = mgh', 'E = Fd', 'B', 11, 6, 'Srednja šola'),
('Kateri zakon opisuje razmerje med napetostjo, tokom in uporom?', 'Fizika', 'Kirchhoffov zakon', 'Ohmov zakon', 'Coulombov zakon', 'Faradayev zakon', 'B', 10, 7, 'Srednja šola'),
('Koliko je hitrost zvoka v zraku pri 20°C?', 'Fizika', '343 m/s', '300 m/s', '340 m/s', '350 m/s', 'A', 11, 8, 'Srednja šola'),
('Katera je SI enota za električni naboj?', 'Fizika', 'Amper', 'Coulomb', 'Volt', 'Ohm', 'B', 10, 9, 'Srednja šola'),
('Kateri princip opisuje vztrajnost telesa?', 'Fizika', 'Newtonov prvi zakon', 'Newtonov drugi zakon', 'Zakon o ohranitvi energije', 'Bernoullijeva enačba', 'A', 10, 10, 'Srednja šola'),

-- Advanced Chemistry
('Kakšna je Avogadrova konstanta?', 'Kemija', '6,022 × 10²³', '6,022 × 10²²', '3,14 × 10²³', '1,602 × 10⁻¹⁹', 'A', 11, 11, 'Srednja šola'),
('Kateri element ima atomsko število 6?', 'Kemija', 'Bor', 'Ogljik', 'Dušik', 'Kisik', 'B', 10, 12, 'Srednja šola'),
('Kakšna je molska masa vode (H₂O)?', 'Kemija', '16 g/mol', '18 g/mol', '20 g/mol', '22 g/mol', 'B', 11, 13, 'Srednja šola'),
('Kateri tip kemijske vezi nastane med kovinami?', 'Kemija', 'Kovalentna', 'Ionska', 'Kovinska', 'Van der Waalsove sile', 'C', 11, 14, 'Srednja šola'),
('Kakšen je pH nevtralne raztopine?', 'Kemija', '6', '7', '8', '9', 'B', 10, 15, 'Srednja šola'),

-- Advanced Biology
('V katerem delu celice poteka celično dihanje?', 'Biologija', 'Jedro', 'Mitohondrij', 'Endoplazmatski retikulum', 'Golgijev aparat', 'B', 11, 16, 'Srednja šola'),
('Koliko kromosomov ima človek?', 'Biologija', '44', '45', '46', '48', 'C', 10, 17, 'Srednja šola'),
('Kateri encim razgrajuje škrob v slini?', 'Biologija', 'Pepsin', 'Amilaza', 'Lipaza', 'Tripsin', 'B', 11, 18, 'Srednja šola'),
('Katera je osnovna enota dednosti?', 'Biologija', 'Kromosom', 'Gen', 'DNA', 'Alel', 'B', 10, 19, 'Srednja šola'),
('V kateri fazi mitoze se kromosomi postavijo v ekvator celice?', 'Biologija', 'Profaza', 'Metafaza', 'Anafaza', 'Telofaza', 'B', 12, 20, 'Srednja šola'),

-- Continue with more challenging questions (21-100)
('Katera je enačba za valovno enačbo?', 'Fizika', 'v = f·λ', 'E = hf', 'F = ma', 'P = VI', 'A', 11, 21, 'Srednja šola'),
('Kateri je rezultat reakcije 2H₂ + O₂ → ?', 'Kemija', 'H₂O₂', '2H₂O', 'H₄O₂', '2H₂O₂', 'B', 10, 22, 'Srednja šola'),
('Katera je funkcija ribosomov?', 'Biologija', 'Sinteza proteinov', 'Sinteza lipidov', 'Celično dihanje', 'Fotosinteza', 'A', 11, 23, 'Srednja šola'),
('Koliko je cos(60°)?', 'Matematika', '0,5', '0,6', '0,7', '0,8', 'A', 11, 24, 'Srednja šola'),
('Katera je enota za električno kapacitivnost?', 'Fizika', 'Farad', 'Henry', 'Weber', 'Tesla', 'A', 12, 25, 'Srednja šola'),

-- Adding more questions to reach 100 for high school (26-100)
('Kateri zakon velja za idealne pline?', 'Kemija', 'Boyle-Mariotte zakon', 'Gay-Lussacov zakon', 'Ideal gas law (PV=nRT)', 'Charles-ov zakon', 'C', 11, 26, 'Srednja šola'),
('Katera je osnovna enota živčnega sistema?', 'Biologija', 'Nevron', 'Sinapse', 'Akson', 'Dendrit', 'A', 10, 27, 'Srednja šola'),
('Koliko je tan(45°)?', 'Matematika', '0', '1', '√2', '√3', 'B', 11, 28, 'Srednja šola'),
('Katera sila drži planete v orbiti?', 'Fizika', 'Elektromagnetna', 'Gravitacijska', 'Jedrska', 'Centrifugalna', 'B', 10, 29, 'Srednja šola'),
('Kateri tip RNA prenašajo genetsko informacijo?', 'Biologija', 'mRNA', 'tRNA', 'rRNA', 'miRNA', 'A', 12, 30, 'Srednja šola'),
('Katera je formula za površino krogle?', 'Matematika', '4πr²', '4πr³', 'πr²', '2πr²', 'A', 11, 31, 'Srednja šola'),
('Kateri element ima največ protonov?', 'Kemija', 'Uran', 'Plutonij', 'Oganesson', 'Torij', 'C', 12, 32, 'Srednja šola'),
('Katera je funkcija belih krvnih celic?', 'Biologija', 'Transport kisika', 'Strjevanje krvi', 'Imunska zaščita', 'Transport hranil', 'C', 10, 33, 'Srednja šola'),
('Koliko je logaritem base 10 od 1000?', 'Matematika', '2', '3', '4', '5', 'B', 11, 34, 'Srednja šola'),
('Katera je enota za magnetni pretok?', 'Fizika', 'Tesla', 'Weber', 'Gauss', 'Henry', 'B', 12, 35, 'Srednja šola'),
('Kateri tip hibridizacije ima ogljik v metanu?', 'Kemija', 'sp', 'sp²', 'sp³', 'sp³d', 'C', 12, 36, 'Srednja šola'),
('V kateri organeli poteka fotosinteza?', 'Biologija', 'Mitohondrij', 'Kloroplast', 'Vakuola', 'Golgijev aparat', 'B', 10, 37, 'Srednja šola'),
('Katera je inverzna funkcija y = ln(x)?', 'Matematika', 'y = e^x', 'y = x²', 'y = 1/x', 'y = √x', 'A', 12, 38, 'Srednja šola'),
('Kateri zakon opisuje elektromagnetno indukcijo?', 'Fizika', 'Ohmov zakon', 'Faradayev zakon', 'Lenzov zakon', 'Gauss zakon', 'B', 11, 39, 'Srednja šola'),
('Katera je molekulska formula glukoze?', 'Kemija', 'C₆H₁₂O₆', 'C₅H₁₀O₅', 'C₆H₁₀O₆', 'C₁₂H₂₂O₁₁', 'A', 11, 40, 'Srednja šola'),
('Kateri proces tvori gamete?', 'Biologija', 'Mitoza', 'Mejoza', 'Citokineza', 'Interfaza', 'B', 11, 41, 'Srednja šola'),
('Koliko je druga derivacija funkcije f(x) = x³?', 'Matematika', '3x²', '6x', '6', 'x²', 'B', 12, 42, 'Srednja šola'),
('Katera je enota za električno induktivnost?', 'Fizika', 'Farad', 'Henry', 'Ohm', 'Siemens', 'B', 12, 43, 'Srednja šola'),
('Kateri je glavni produkt fotosinteze?', 'Biologija', 'Kisik', 'Glukoza', 'Ogljikov dioksid', 'Voda', 'B', 10, 44, 'Srednja šola'),
('Katera je oxidacijska stopnja železa v Fe₂O₃?', 'Kemija', '+2', '+3', '+4', '+1', 'B', 11, 45, 'Srednja šola'),
('Koliko je integral ∫1/x dx?', 'Matematika', 'ln|x| + C', '1/x² + C', 'x + C', '-1/x² + C', 'A', 12, 46, 'Srednja šola'),
('Katera sila deluje med nabitimi delci?', 'Fizika', 'Gravitacijska', 'Elektrostatična', 'Magnetna', 'Jedrska', 'B', 11, 47, 'Srednja šola'),
('Kateri encim odpira DNA vijačnico?', 'Biologija', 'DNA polimeraza', 'Helikaza', 'Primaza', 'Ligaza', 'B', 12, 48, 'Srednja šola'),
('Katera je splošna formula alkanov?', 'Kemija', 'CnH2n', 'CnH2n+2', 'CnH2n-2', 'CnHn', 'B', 11, 49, 'Srednja šola'),
('Koliko je vrednost funkcije f(x) = x² - 3x + 2 pri x = 2?', 'Matematika', '0', '1', '2', '-1', 'A', 11, 50, 'Srednja šola'),

-- Adding final 50 questions to reach 100 for high school (51-100)
('Kateri zakon opisuje obnašanje svetlobe?', 'Fizika', 'Snellov zakon', 'Hookev zakon', 'Ohmov zakon', 'Coulombov zakon', 'A', 11, 51, 'Srednja šola'),
('Katera je funkcija jetra?', 'Biologija', 'Filtriranje krvi', 'Detoksikacija', 'Dihanje', 'Kroženje', 'B', 10, 52, 'Srednja šola'),
('Koliko je rešitev enačbe x² - 5x + 6 = 0?', 'Matematika', 'x = 2, 3', 'x = 1, 6', 'x = -2, -3', 'x = 2, -3', 'A', 11, 53, 'Srednja šola'),
('Katera je SI osnovna enota za količino snovi?', 'Kemija', 'Gram', 'Mol', 'Liter', 'Kilogram', 'B', 10, 54, 'Srednja šola'),
('Kateri del živčevja nadzoruje reflekse?', 'Biologija', 'Veliki možgani', 'Mali možgani', 'Hrbtenjača', 'Hipotalamus', 'C', 11, 55, 'Srednja šola'),
('Koliko je arcsin(1/2)?', 'Matematika', '30°', '45°', '60°', '90°', 'A', 12, 56, 'Srednja šola'),
('Katera je enota za frekvenco?', 'Fizika', 'Hertz', 'Decibel', 'Watt', 'Joule', 'A', 10, 57, 'Srednja šola'),
('Kateri tip kemijske reakcije je 2H₂O₂ → 2H₂O + O₂?', 'Kemija', 'Sinteza', 'Razgradnja', 'Nadomestitev', 'Dviganje', 'B', 11, 58, 'Srednja šola'),
('Kateri hormon uravnava krvni sladkor?', 'Biologija', 'Adrenalin', 'Insulin', 'Tiroksin', 'Kortizol', 'B', 11, 59, 'Srednja šola'),
('Katera je enačba krožnice s središčem v koordinatnem izhodišču?', 'Matematika', 'x² + y² = r²', 'x + y = r', 'xy = r²', 'x² - y² = r²', 'A', 11, 60, 'Srednja šola'),
('Kateri fizikalni pojav opisuje Dopplerjev efekt?', 'Fizika', 'Lom svetlobe', 'Sprememba frekvence', 'Interferenca', 'Polarizacija', 'B', 12, 61, 'Srednja šola'),
('Kateri biomolekul shranjuje genetske informacije?', 'Biologija', 'Protein', 'Lipid', 'DNA', 'Ogljikohidrat', 'C', 10, 62, 'Srednja šola'),
('Koliko je e (Eulerjevo število) približno?', 'Matematika', '2,618', '2,718', '3,141', '1,618', 'B', 12, 63, 'Srednja šola'),
('Katera je oznaka za električno prevodnost?', 'Fizika', 'R', 'G', 'C', 'L', 'B', 11, 64, 'Srednja šola'),
('Kateri element je osnova organskih spojin?', 'Kemija', 'Vodik', 'Kisik', 'Ogljik', 'Dušik', 'C', 10, 65, 'Srednja šola'),
('Katera krvožilna skupina dovaja kri v srce?', 'Biologija', 'Arterije', 'Vene', 'Kapilare', 'Limfatike', 'B', 10, 66, 'Srednja šola'),
('Katera je formula za volumen stožca?', 'Matematika', 'πr²h', '⅓πr²h', '2πrh', '4πr²', 'B', 11, 67, 'Srednja šola'),
('Kateri princip opisuje zakon o ohranjenosti energije?', 'Fizika', 'Prvi termodynamični zakon', 'Drugi termodynamični zakon', 'Bernoullijeva enačba', 'Pascalov zakon', 'A', 11, 68, 'Srednja šola'),
('Katera je elektronska konfiguracija neona?', 'Kemija', '1s² 2s² 2p⁶', '1s² 2s² 2p⁴', '1s² 2s² 2p⁵', '1s² 2s² 2p³', 'A', 11, 69, 'Srednja šola'),
('V katerem procesu se ATP sintetizira iz ADP?', 'Biologija', 'Glikoliza', 'Citratni cikel', 'Elektronski transport', 'Fotosinteza', 'C', 12, 70, 'Srednja šola'),
('Koliko je limita lim(x→∞) 1/x?', 'Matematika', '0', '1', '∞', 'Ne obstaja', 'A', 12, 71, 'Srednja šola'),
('Katera je osnovna enota električne napetosti?', 'Fizika', 'Amper', 'Volt', 'Ohm', 'Watt', 'B', 10, 72, 'Srednja šola'),
('Kateri tip reakcije je neutralizacija?', 'Kemija', 'Kislina + baza', 'Oksidacija', 'Redukcija', 'Hidroliza', 'A', 10, 73, 'Srednja šola'),
('Kateri del ušesa je odgovoren za sluh?', 'Biologija', 'Zunanje uho', 'Srednje uho', 'Notranje uho', 'Bobničnica', 'C', 11, 74, 'Srednja šola'),
('Katera je derivacija funkcije sin(x)?', 'Matematika', 'cos(x)', '-cos(x)', 'sin(x)', '-sin(x)', 'A', 12, 75, 'Srednja šola'),
('Kateri zakon velja za odboj svetlobe?', 'Fizika', 'Vpadni kot = odbojni kot', 'n₁sin θ₁ = n₂sin θ₂', 'E = hf', 'F = ma', 'A', 11, 76, 'Srednja šola'),
('Katera je splošna formula alkoholov?', 'Kemija', 'CnH2n+1OH', 'CnH2nOH', 'CnH2n-1OH', 'CnHnOH', 'A', 11, 77, 'Srednja šola'),
('Kateri del možganov kontrolira govor?', 'Biologija', 'Brocovo področje', 'Wernickeovo področje', 'Mali možgani', 'Hipokampus', 'A', 12, 78, 'Srednja šola'),
('Koliko je arccos(0)?', 'Matematika', '0°', '30°', '60°', '90°', 'D', 12, 79, 'Srednja šola'),
('Katera je enota za tlak?', 'Fizika', 'Pascal', 'Newton', 'Joule', 'Watt', 'A', 10, 80, 'Srednja šola'),
('Kateri encim razgrajuje laktozo?', 'Biologija', 'Laktaza', 'Maltaza', 'Sukreza', 'Amilaza', 'A', 11, 81, 'Srednja šola'),
('Katera je rešitev enačbe log₂(x) = 3?', 'Matematika', 'x = 6', 'x = 8', 'x = 9', 'x = 12', 'B', 11, 82, 'Srednja šola'),
('Kateri pojav nastane pri interference svetlobe?', 'Fizika', 'Ojačitev in šibitev', 'Polarizacija', 'Disperzija', 'Difrakcija', 'A', 12, 83, 'Srednja šola'),
('Katera je oxidacijska stopnja vodika v H₂O?', 'Kemija', '-1', '+1', '0', '+2', 'B', 11, 84, 'Srednja šola'),
('Kateri tip mišic je srčna mišica?', 'Biologija', 'Skeletna', 'Gladka', 'Srčna', 'Prečnočrtasta', 'C', 10, 85, 'Srednja šola'),
('Katera je formula za geometrično sredino dveh števil a in b?', 'Matematika', '(a+b)/2', '√(ab)', '2ab/(a+b)', 'ab', 'B', 11, 86, 'Srednja šola'),
('Katera je osnovna enota za delo?', 'Fizika', 'Joule', 'Watt', 'Newton', 'Pascal', 'A', 10, 87, 'Srednja šola'),
('Kateri ion povzroča kislost raztopine?', 'Kemija', 'OH⁻', 'H⁺', 'Na⁺', 'Cl⁻', 'B', 10, 88, 'Srednja šola'),
('Kateri proces tvori novo DNA?', 'Biologija', 'Transkripcija', 'Translacija', 'Replikacija', 'Mutacija', 'C', 11, 89, 'Srednja šola'),
('Koliko je integral ∫cos(x) dx?', 'Matematika', 'sin(x) + C', '-sin(x) + C', 'cos(x) + C', '-cos(x) + C', 'A', 12, 90, 'Srednja šola'),
('Kateri zakon opisuje magnetno silo?', 'Fizika', 'F = qvB', 'F = ma', 'F = kQq/r²', 'F = mg', 'A', 12, 91, 'Srednja šola'),
('Katera je molekulska masa ogljikovega dioksida?', 'Kemija', '28 g/mol', '32 g/mol', '44 g/mol', '46 g/mol', 'C', 11, 92, 'Srednja šola'),
('Kateri del ledvic filtrira kri?', 'Biologija', 'Glomeruli', 'Nefron', 'Kanalčki', 'Mehur', 'A', 11, 93, 'Srednja šola'),
('Katera je enačba hiperbole?', 'Matematika', 'x²/a² - y²/b² = 1', 'x²/a² + y²/b² = 1', 'y = k/x', 'x² + y² = r²', 'A', 12, 94, 'Srednja šola'),
('Kateri pojav opisuje popolni odboj svetlobe?', 'Fizika', 'Refrakcija', 'Difuzija', 'Totalna refleksija', 'Absorbcija', 'C', 11, 95, 'Srednja šola'),
('Kateri tip hibridizacije ima ogljik v acetilenu?', 'Kemija', 'sp', 'sp²', 'sp³', 'sp³d', 'A', 12, 96, 'Srednja šola'),
('Kateri del živčnega sistema kontrolira nezavedno dihanje?', 'Biologija', 'Veliki možgani', 'Mali možgani', 'Podaljšana hrbtenjača', 'Hipotalamus', 'C', 11, 97, 'Srednja šola'),
('Koliko je vrednost π (pi) na tri decimalna mesta?', 'Matematika', '3,141', '3,142', '3,143', '3,140', 'B', 10, 98, 'Srednja šola'),
('Katera je enota za električno delo?', 'Fizika', 'Joule', 'kWh', 'Oba odgovora', 'Noben odgovor', 'C', 11, 99, 'Srednja šola'),
('Kateri proces omogoča rastlinam pridobivanje dušika?', 'Biologija', 'Fotosinteza', 'Fiksacija dušika', 'Transpiracija', 'Celično dihanje', 'B', 12, 100, 'Srednja šola');