-- Add more questions focusing on underrepresented grades (6, 9, 10, 12) and filling gaps
-- This batch adds ~200 questions to better balance the grade distribution

INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, grade_level, difficulty_order, subject, category) VALUES

-- Grade 6 questions (current: 23, adding 25 more)
('Katera planeta je najbližja Soncu?', 'Venera', 'Merkur', 'Zemlja', 'Mars', 'B', 6, 1, 'Naravoslovje', 'Šola'),
('Koliko je 15% od 200?', '25', '30', '35', '40', 'B', 6, 2, 'Matematika', 'Šola'),
('Kateri sistem organov skrbi za prenos kisika po telesu?', 'Prebavni', 'Dihalni', 'Krvni', 'Živčni', 'C', 6, 3, 'Naravoslovje', 'Šola'),
('Kdaj se je zgodila bitka pri Sisku?', '1593', '1571', '1664', '1689', 'A', 6, 4, 'Zgodovina', 'Šola'),
('Katera je največja reka v Sloveniji?', 'Drava', 'Sava', 'Soča', 'Mura', 'B', 6, 1, 'Geografija', 'Šola'),
('Koliko je površina pravokotnika s stranicama 8 cm in 12 cm?', '96 cm²', '40 cm²', '20 cm²', '48 cm²', 'A', 6, 2, 'Matematika', 'Šola'),
('Kateri gas izdihavamo?', 'Kisik', 'Ogljikov dioksid', 'Dušik', 'Vodik', 'B', 6, 1, 'Naravoslovje', 'Šola'),
('Kdo je napisal "Jurčiček"?', 'Ivan Cankar', 'Josip Jurčič', 'Fran Levstik', 'Anton Aškerc', 'B', 6, 3, 'Slovenščina', 'Šola'),
('Koliko strani ima kocka?', '4', '6', '8', '12', 'B', 6, 1, 'Matematika', 'Šola'),
('Katera celina je največja?', 'Afrika', 'Azija', 'Evropa', 'Severna Amerika', 'B', 6, 2, 'Geografija', 'Šola'),
('Kaj je fotosinteza?', 'Dihanje rastlin', 'Tvorba hrane iz svetlobe', 'Rast rastlin', 'Cvetenje rastlin', 'B', 6, 3, 'Naravoslovje', 'Šola'),
('Koliko je 3⁴?', '12', '64', '81', '36', 'C', 6, 4, 'Matematika', 'Šola'),
('Kateri ocean je največji?', 'Atlantski', 'Indijski', 'Tihi', 'Arktični', 'C', 6, 2, 'Geografija', 'Šola'),
('Kdo je prvi človek, ki je stopil na Luno?', 'Buzz Aldrin', 'Neil Armstrong', 'John Glenn', 'Yuri Gagarin', 'B', 6, 4, 'Zgodovina', 'Šola'),
('Katera snov ne prevaja elektrike?', 'Baker', 'Železo', 'Guma', 'Aluminij', 'C', 6, 3, 'Naravoslovje', 'Šola'),
('Koliko je obseg kroga s polmerom 5 cm? (π ≈ 3,14)', '15,7 cm', '31,4 cm', '78,5 cm', '25 cm', 'B', 6, 5, 'Matematika', 'Šola'),
('Katera je glavna reka Egipta?', 'Nil', 'Kongo', 'Niger', 'Zambezi', 'A', 6, 2, 'Geografija', 'Šola'),
('Kaj pomeni beseda "bibliofil"?', 'Ljubitelj knjig', 'Pisatelj', 'Knjižničar', 'Trgovec s knjigami', 'A', 6, 4, 'Slovenščina', 'Šola'),
('Kateri element ima kemijski simbol O?', 'Ogljik', 'Kisik', 'Zlato', 'Železo', 'B', 6, 2, 'Naravoslovje', 'Šola'),
('Koliko je 2/3 od 90?', '30', '45', '60', '75', 'C', 6, 3, 'Matematika', 'Šola'),
('Katera evropska država ima obliko škornja?', 'Španija', 'Francija', 'Italija', 'Grčija', 'C', 6, 2, 'Geografija', 'Šola'),
('Kaj študira botanika?', 'Živali', 'Rastline', 'Minerale', 'Zvezde', 'B', 6, 3, 'Naravoslovje', 'Šola'),
('Kdo je sestavil slovensko himno?', 'France Prešeren', 'Stanko Premrl', 'Ivan Cankar', 'Anton Aškerc', 'B', 6, 4, 'Slovenščina', 'Šola'),
('Koliko stopinj ima pravokotni kot?', '45°', '60°', '90°', '180°', 'C', 6, 1, 'Matematika', 'Šola'),
('Katera gorska veriga ločuje Evropo od Azije?', 'Alpe', 'Himalaja', 'Ural', 'Karpati', 'C', 6, 4, 'Geografija', 'Šola'),

-- Grade 9 questions (current: 25, adding 25 more)
('Katera je formula za izračun volumna krogle?', 'V = πr²h', 'V = 4/3πr³', 'V = πr²', 'V = 2πr³', 'B', 9, 4, 'Matematika', 'Šola'),
('Kdaj se je začela prva svetovna vojna?', '1912', '1914', '1916', '1918', 'B', 9, 3, 'Zgodovina', 'Šola'),
('Kaj je mitoza?', 'Delitev celic', 'Spajanje celic', 'Smrt celic', 'Rast celic', 'A', 9, 4, 'Biologija', 'Šola'),
('Koliko je √144?', '11', '12', '13', '14', 'B', 9, 2, 'Matematika', 'Šola'),
('Kateri plini sestavljajo atmosfero?', 'Samo kisik', 'Dušik in kisik', 'Samo dušik', 'Ogljikov dioksid', 'B', 9, 3, 'Kemija', 'Šola'),
('Kdo je napisal "Romeo in Julija"?', 'Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Oscar Wilde', 'B', 9, 2, 'Književnost', 'Šola'),
('Kaj je električna moč?', 'I × U', 'U / I', 'I / U', 'U × R', 'A', 9, 4, 'Fizika', 'Šola'),
('Katera država je bila razdeljena po drugi svetovni vojni?', 'Italija', 'Francija', 'Nemčija', 'Poljska', 'C', 9, 3, 'Zgodovina', 'Šola'),
('Koliko je sin 30°?', '0,5', '0,707', '0,866', '1', 'A', 9, 4, 'Matematika', 'Šola'),
('Kateri organ proizvaja inzulin?', 'Jetra', 'Ledvici', 'Trebušna slinavka', 'Želodec', 'C', 9, 4, 'Biologija', 'Šola'),
('Kaj študija ekonomija?', 'Politiko', 'Gospodarstvo', 'Družbo', 'Kulturo', 'B', 9, 2, 'Družboslovje', 'Šola'),
('Katera sila drži predmete na Zemlji?', 'Magnetna', 'Gravitacijska', 'Električna', 'Jedrska', 'B', 9, 2, 'Fizika', 'Šola'),
('Kdo je odkril penicillin?', 'Louis Pasteur', 'Alexander Fleming', 'Marie Curie', 'Albert Einstein', 'B', 9, 4, 'Zgodovina', 'Šola'),
('Koliko je 5! (fakulteta)?', '25', '120', '625', '3125', 'B', 9, 4, 'Matematika', 'Šola'),
('Katera je kemijska formula vode?', 'H₂O', 'HO₂', 'H₂O₂', 'H₃O', 'A', 9, 1, 'Kemija', 'Šola'),
('Kaj je demokracija?', 'Vladavina enega', 'Vladavina maloštevilnih', 'Vladavina ljudstva', 'Vladavina vojske', 'C', 9, 2, 'Družboslovje', 'Šola'),
('Kateri je največji organ človeškega telesa?', 'Jetra', 'Pljuča', 'Koža', 'Možgani', 'C', 9, 2, 'Biologija', 'Šola'),
('Koliko je log₁₀(100)?', '1', '2', '10', '100', 'B', 9, 4, 'Matematika', 'Šola'),
('Kdo je napisal "1984"?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells', 'B', 9, 4, 'Književnost', 'Šola'),
('Kaj je elektroliza?', 'Gorenje', 'Razkroj z elektriko', 'Taljenje', 'Kristalizacija', 'B', 9, 4, 'Kemija', 'Šola'),
('Katera celina ima največ držav?', 'Azija', 'Afrika', 'Evropa', 'Južna Amerika', 'B', 9, 3, 'Geografija', 'Šola'),
('Kaj je fotón?', 'Delček svetlobe', 'Vrsta atoma', 'Elektronski del', 'Magnetni pol', 'A', 9, 5, 'Fizika', 'Šola'),
('Kdaj je padel Berlinski zid?', '1987', '1989', '1991', '1993', 'B', 9, 4, 'Zgodovina', 'Šola'),
('Koliko je 2x² + 3x - 5, če je x = 2?', '5', '7', '9', '11', 'C', 9, 4, 'Matematika', 'Šola'),
('Kateri sistem skrbi za obrambo organizma?', 'Prebavni', 'Imunski', 'Endokrini', 'Živčni', 'B', 9, 3, 'Biologija', 'Šola'),

-- Grade 10 questions (current: 24, adding 25 more)
('Kaj je derivat funkcije f(x) = x²?', 'x', '2x', 'x²', '2x²', 'B', 10, 4, 'Matematika', 'Šola'),
('Kdo je razvil teorijo relativnosti?', 'Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Max Planck', 'B', 10, 3, 'Fizika', 'Šola'),
('Kaj je DNA?', 'Beljakovina', 'Maščoba', 'Nukleinska kislina', 'Ogljikov hidrat', 'C', 10, 4, 'Biologija', 'Šola'),
('Koliko je integral ∫2x dx?', 'x²', 'x² + C', '2x²', 'x² + C', 'B', 10, 5, 'Matematika', 'Šola'),
('Katera je najmanjša enota snovi?', 'Molekula', 'Atom', 'Ion', 'Elektron', 'B', 10, 2, 'Kemija', 'Šola'),
('Kdo je napisal "Krst pri Savici"?', 'Ivan Cankar', 'France Prešeren', 'Josip Jurčič', 'Anton Aškerc', 'B', 10, 3, 'Književnost', 'Šola'),
('Kaj je AC tok?', 'Enosmerni tok', 'Izmenični tok', 'Magnetni tok', 'Statični tok', 'B', 10, 3, 'Fizika', 'Šola'),
('Kateri je najstarejši družbeni red?', 'Fevdalizem', 'Kapitalizem', 'Suženjstvo', 'Socializem', 'C', 10, 4, 'Zgodovina', 'Šola'),
('Koliko je lim(x→0) sin(x)/x?', '0', '1', '∞', 'Nedefiniran', 'B', 10, 5, 'Matematika', 'Šola'),
('Kaj je RNA?', 'Ribonukleinska kislina', 'Beljakovina', 'Encim', 'Hormon', 'A', 10, 4, 'Biologija', 'Šola'),
('Kdo je odkril radioaktivnost?', 'Marie Curie', 'Henri Becquerel', 'Ernest Rutherford', 'Dmitri Mendeleev', 'B', 10, 4, 'Kemija', 'Šola'),
('Kaj pomeni GDP?', 'Bruto domači proizvod', 'Globalni razvoj', 'Državni proračun', 'Gospodarska rast', 'A', 10, 3, 'Ekonomija', 'Šola'),
('Katera je enačba premice?', 'y = ax + b', 'y = ax²', 'y = a/x', 'y = aˣ', 'A', 10, 2, 'Matematika', 'Šola'),
('Kaj je evolucija?', 'Napredek tehnologije', 'Razvoj vrst', 'Rast populacije', 'Klimatske spremembe', 'B', 10, 3, 'Biologija', 'Šola'),
('Kdo je ustanovil psihoanalizolo?', 'Carl Jung', 'Sigmund Freud', 'Alfred Adler', 'Wilhelm Wundt', 'B', 10, 4, 'Psihologija', 'Šola'),
('Kaj je entropija?', 'Energija', 'Moč', 'Nered sistema', 'Hitrost', 'C', 10, 5, 'Fizika', 'Šola'),
('Katera je osnovna enota električnega naboja?', 'Volt', 'Amper', 'Coulomb', 'Ohm', 'C', 10, 3, 'Fizika', 'Šola'),
('Kdo je napisal "Odisejado"?', 'Homer', 'Sofokles', 'Evripid', 'Aristotel', 'A', 10, 3, 'Književnost', 'Šola'),
('Koliko je e⁰?', '0', '1', 'e', '∞', 'B', 10, 3, 'Matematika', 'Šola'),
('Kaj je gen?', 'Celica', 'Dednostni dejavnik', 'Beljakovina', 'Encim', 'B', 10, 3, 'Biologija', 'Šola'),
('Kateri plin je najštevilčnejši v atmosferi?', 'Kisik', 'Dušik', 'Argon', 'Ogljikov dioksid', 'B', 10, 2, 'Kemija', 'Šola'),
('Kdaj se je zgodila oktobrska revolucija?', '1905', '1917', '1918', '1922', 'B', 10, 4, 'Zgodovina', 'Šola'),
('Kaj je logaritem?', 'Obratna funkcija potence', 'Vrsta enačbe', 'Matematična konstanta', 'Geometrijska funkcija', 'A', 10, 4, 'Matematika', 'Šola'),
('Kdo je odkril dvojno vijačnico DNA?', 'Watson in Crick', 'Mendel', 'Darwin', 'Pasteur', 'A', 10, 5, 'Biologija', 'Šola'),
('Kaj je inflacija?', 'Padec cen', 'Rast cen', 'Stabilne cene', 'Menjava valut', 'B', 10, 3, 'Ekonomija', 'Šola'),

-- Grade 12 questions (current: 29, adding 30 more)
('Kaj je kvantna mehanika?', 'Klasična fizika', 'Fizika atomskih delcev', 'Teorija relativnosti', 'Termodinamika', 'B', 12, 5, 'Fizika', 'Šola'),
('Koliko je ∫e^x dx?', 'e^x', 'xe^x', 'e^x + C', 'ln(x)', 'C', 12, 5, 'Matematika', 'Šola'),
('Kaj je transcendens?', 'Iracionalno število', 'Število, ki ni algebrsko', 'Kompleksno število', 'Naravno število', 'B', 12, 5, 'Matematika', 'Šola'),
('Kdo je napisal "Faust"?', 'Friedrich Schiller', 'Johann Wolfgang Goethe', 'Heinrich Heine', 'Thomas Mann', 'B', 12, 4, 'Književnost', 'Šola'),
('Kaj je fuzija?', 'Cepitev jeder', 'Spajanje jeder', 'Radioaktivni razpad', 'Ionizacija', 'B', 12, 5, 'Fizika', 'Šola'),
('Kaj študija fenomenologija?', 'Naravoslovje', 'Zavest in izkušnje', 'Logiko', 'Etiko', 'B', 12, 5, 'Filozofija', 'Šola'),
('Koliko je derivat ln(x)?', '1/x', 'x', 'ln(x)', 'e^x', 'A', 12, 4, 'Matematika', 'Šola'),
('Kaj je alelopacija?', 'Medsebojno učinkovanje rastlin', 'Rast rastlin', 'Razmnoževanje rastlin', 'Fotosinteza', 'A', 12, 5, 'Biologija', 'Šola'),
('Kdo je ustanovil kemijsko tabelo?', 'Antoine Lavoisier', 'Dmitri Mendeleev', 'John Dalton', 'Robert Boyle', 'B', 12, 4, 'Kemija', 'Šola'),
('Kaj je eksistencializem?', 'Filozofska smer', 'Umetniška smer', 'Politična teorija', 'Znanstvena metoda', 'A', 12, 5, 'Filozofija', 'Šola'),
('Koliko je ∫1/x dx?', 'ln|x| + C', 'x + C', '1/x² + C', 'e^x + C', 'A', 12, 5, 'Matematika', 'Šola'),
('Kaj je PCR?', 'Verižna reakcija polimeraz', 'Proteinska sinteza', 'Celična delitev', 'Metabolizem', 'A', 12, 5, 'Biologija', 'Šola'),
('Kdo je napisal "Vojn in mir"?', 'Fjodor Dostojevski', 'Lev Tolstoj', 'Anton Čehov', 'Ivan Turgenjev', 'B', 12, 4, 'Književnost', 'Šola'),
('Kaj je entalpija?', 'Toplota sistema', 'Delo sistema', 'Energija sistema', 'Moč sistema', 'A', 12, 5, 'Kemija', 'Šola'),
('Koliko je sin²x + cos²x?', '0', '1', '2', 'Odvisno od x', 'B', 12, 3, 'Matematika', 'Šola'),
('Kaj je apoptoza?', 'Celična smrt', 'Celična delitev', 'Celična rast', 'Celična diferenciacija', 'A', 12, 5, 'Biologija', 'Šola'),
('Kdo je razvil kvantno teorijo?', 'Albert Einstein', 'Max Planck', 'Niels Bohr', 'Werner Heisenberg', 'B', 12, 5, 'Fizika', 'Šola'),
('Kaj je paradigma?', 'Znanstveni model', 'Hipoteza', 'Teorija', 'Eksperiment', 'A', 12, 4, 'Metodologija', 'Šola'),
('Koliko je e^(iπ)?', '-1', '1', 'i', '-i', 'A', 12, 5, 'Matematika', 'Šola'),
('Kaj je polimerizacija?', 'Kemijska reakcija', 'Fizikalni proces', 'Biološki proces', 'Vse našteto', 'A', 12, 5, 'Kemija', 'Šola'),
('Kdo je napisal "Metamorfozo"?', 'Franz Kafka', 'James Joyce', 'Marcel Proust', 'Virginia Woolf', 'A', 12, 5, 'Književnost', 'Šola'),
('Kaj je superkonduktivnost?', 'Zelo dobro prevajanje elektrike', 'Prevajanje brez upora', 'Magnetno prevajanje', 'Toplotno prevajanje', 'B', 12, 5, 'Fizika', 'Šola'),
('Koliko je integral ∫sin(x)dx?', '-cos(x) + C', 'cos(x) + C', 'sin(x) + C', '-sin(x) + C', 'A', 12, 4, 'Matematika', 'Šola'),
('Kaj je epigenetika?', 'Dednost brez sprememb DNA', 'Mutacije genov', 'Gensko inženirstvo', 'Evolucija', 'A', 12, 5, 'Biologija', 'Šola'),
('Kdo je napisal "Ulysses"?', 'James Joyce', 'Samuel Beckett', 'Oscar Wilde', 'W.B. Yeats', 'A', 12, 5, 'Književnost', 'Šola'),
('Kaj je kataliza?', 'Pospešitev reakcije', 'Upočasnitev reakcije', 'Zaustavitev reakcije', 'Obračanje reakcije', 'A', 12, 4, 'Kemija', 'Šola'),
('Koliko je arctg(1)?', 'π/6', 'π/4', 'π/3', 'π/2', 'B', 12, 4, 'Matematika', 'Šola'),
('Kaj je morfogeneza?', 'Oblikovanje organizma', 'Rast organizma', 'Razmnoževanje organizma', 'Smrt organizma', 'A', 12, 5, 'Biologija', 'Šola'),
('Kdo je razvil strukturalizem?', 'Ferdinand de Saussure', 'Noam Chomsky', 'Roland Barthes', 'Michel Foucault', 'A', 12, 5, 'Jezikoslovje', 'Šola'),
('Kaj je superpozicija?', 'Seštevanje valov', 'Interferenca svetlobe', 'Kvantno stanje', 'Vse našteto', 'D', 12, 5, 'Fizika', 'Šola'),

-- Additional questions for other grades to balance the total
-- Grade 7 questions (adding 15 more)
('Koliko je 3x + 5 = 14, x = ?', '2', '3', '4', '5', 'B', 7, 3, 'Matematika', 'Šola'),
('Kdo je napisal "Mali princ"?', 'Jules Verne', 'Antoine de Saint-Exupéry', 'Lewis Carroll', 'Roald Dahl', 'B', 7, 2, 'Književnost', 'Šola'),
('Katera celina je najmanjša?', 'Evropa', 'Avstralija', 'Antarktika', 'Južna Amerika', 'B', 7, 2, 'Geografija', 'Šola'),
('Kaj je ekosistem?', 'Skupnost organizmov', 'Okolje samo', 'Organizmi in okolje skupaj', 'Samo rastline', 'C', 7, 3, 'Naravoslovje', 'Šola'),
('Koliko je 5² - 3²?', '16', '14', '18', '12', 'A', 7, 2, 'Matematika', 'Šola'),
('Kateri je najdaljši dan v letu?', '21. junij', '21. marec', '21. september', '21. december', 'A', 7, 2, 'Naravoslovje', 'Šola'),
('Kdo je odkril Ameriko?', 'Vasco da Gama', 'Kristof Kolumb', 'Amerigo Vespucci', 'Fernando Magellan', 'B', 7, 2, 'Zgodovina', 'Šola'),
('Koliko je 7/10 v odstotkih?', '7%', '70%', '0,7%', '700%', 'B', 7, 2, 'Matematika', 'Šola'),
('Katera je najvišja gora na svetu?', 'K2', 'Mount Everest', 'Kilimandžaro', 'Mont Blanc', 'B', 7, 1, 'Geografija', 'Šola'),
('Kaj je gravitacija?', 'Sila odboja', 'Sila privlaka', 'Sila trenja', 'Magnetna sila', 'B', 7, 2, 'Fizika', 'Šola'),
('Kdo je napisal "Robinson Crusoe"?', 'Daniel Defoe', 'Jonathan Swift', 'Charles Dickens', 'Mark Twain', 'A', 7, 3, 'Književnost', 'Šola'),
('Koliko je volumen kvadra 2×3×4?', '24', '9', '14', '48', 'A', 7, 3, 'Matematika', 'Šola'),
('Katera država je največja po površini?', 'Kanada', 'Kitajska', 'Rusija', 'ZDA', 'C', 7, 2, 'Geografija', 'Šola'),
('Kaj je vertebrat?', 'Žival s hrbtenico', 'Žival brez hrbtenice', 'Rastlina', 'Gliva', 'A', 7, 2, 'Biologija', 'Šola'),
('Koliko je 15 × 12?', '180', '170', '190', '160', 'A', 7, 2, 'Matematika', 'Šola'),

-- Grade 8 questions (adding 15 more)
('Kaj je kvadratna enačba?', 'ax + b = 0', 'ax² + bx + c = 0', 'ax³ + b = 0', 'a/x + b = 0', 'B', 8, 3, 'Matematika', 'Šola'),
('Kdo je napisal "1001 noč"?', 'Neznan avtor', 'Omar Hajam', 'Rumi', 'Al-Džahiz', 'A', 8, 3, 'Književnost', 'Šola'),
('Katera je formula za pot?', 's = vt', 'v = st', 't = sv', 's = v/t', 'A', 8, 2, 'Fizika', 'Šola'),
('Koliko je -3 + 5 × 2?', '4', '7', '10', '-6', 'B', 8, 3, 'Matematika', 'Šola'),
('Kateri sistem organov skrbi za gibanje?', 'Mišični', 'Kostni', 'Mišično-kostni', 'Živčni', 'C', 8, 2, 'Biologija', 'Šola'),
('Kdaj se je zgodila francoska revolucija?', '1789', '1799', '1804', '1815', 'A', 8, 3, 'Zgodovina', 'Šola'),
('Kaj je sila?', 'Hitrost', 'Delo', 'Push ali pull', 'Energija', 'C', 8, 2, 'Fizika', 'Šola'),
('Koliko je √64?', '6', '7', '8', '9', 'C', 8, 2, 'Matematika', 'Šola'),
('Katera je glavna funkcija srca?', 'Dihanje', 'Črpanje krvi', 'Prebava', 'Filtriranje', 'B', 8, 2, 'Biologija', 'Šola'),
('Kdo je napisal "Don Kihot"?', 'Cervantes', 'Lope de Vega', 'Calderón', 'Góngora', 'A', 8, 3, 'Književnost', 'Šola'),
('Koliko je 2⁵?', '10', '25', '32', '64', 'C', 8, 3, 'Matematika', 'Šola'),
('Katera je kemijska formula kuhinjske soli?', 'NaCl', 'KCl', 'CaCl₂', 'MgCl₂', 'A', 8, 2, 'Kemija', 'Šola'),
('Kdo je napisal "Ilado"?', 'Homer', 'Hesiod', 'Sofokles', 'Evripid', 'A', 8, 2, 'Književnost', 'Šola'),
('Kaj je lastna teža?', 'Masa × gravitacija', 'Masa / gravitacija', 'Gravitacija - masa', 'Masa + gravitacija', 'A', 8, 3, 'Fizika', 'Šola'),
('Koliko je 25% od 80?', '15', '20', '25', '30', 'B', 8, 2, 'Matematika', 'Šola'),

-- Grade 11 questions (adding 20 more)
('Kaj je kompleksno število?', 'a + bi', 'Negativno število', 'Iracionalno število', 'Decimalno število', 'A', 11, 4, 'Matematika', 'Šola'),
('Kdo je napisal "Sto let samote"?', 'Mario Vargas Llosa', 'Gabriel García Márquez', 'Isabel Allende', 'Octavio Paz', 'B', 11, 4, 'Književnost', 'Šola'),
('Kaj je elektromagnetno valovanje?', 'Zvočni val', 'Svetlobni val', 'Električni tok', 'Magnetno polje', 'B', 11, 4, 'Fizika', 'Šola'),
('Koliko je cos(π/2)?', '0', '1', '-1', '1/2', 'A', 11, 3, 'Matematika', 'Šola'),
('Kaj je homeostaza?', 'Ravnotežje v organizmu', 'Bolezen', 'Rast', 'Smrt', 'A', 11, 4, 'Biologija', 'Šola'),
('Kdo je napisal teorijo o izvoru vrst?', 'Gregor Mendel', 'Charles Darwin', 'Jean-Baptiste Lamarck', 'Alfred Wallace', 'B', 11, 4, 'Biologija', 'Šola'),
('Kaj je periodična tabela?', 'Seznam elementov', 'Urejen seznam elementov', 'Kemijske reakcije', 'Molekule', 'B', 11, 3, 'Kemija', 'Šola'),
('Koliko je tg(45°)?', '0', '1', '√3', '1/√3', 'B', 11, 3, 'Matematika', 'Šola'),
('Kaj je fotoelektrični efekt?', 'Svetloba tvori elektrone', 'Elektrika tvori svetlobo', 'Magnetizem', 'Radioaktivnost', 'A', 11, 5, 'Fizika', 'Šola'),
('Kdo je napisal "Puščavnik"?', 'Ivan Cankar', 'Josip Jurčič', 'France Prešeren', 'Anton Aškerc', 'A', 11, 4, 'Književnost', 'Šola'),
('Kaj je molarnost?', 'Količina snovi na liter', 'Masa na liter', 'Volumen na maso', 'Število delcev', 'A', 11, 4, 'Kemija', 'Šola'),
('Koliko je e (Eulerjevo število) približno?', '2,718', '3,141', '1,414', '1,732', 'A', 11, 4, 'Matematika', 'Šola'),
('Kaj je meioza?', 'Redukcijska delitev', 'Običajna delitev', 'Rast celic', 'Smrt celic', 'A', 11, 4, 'Biologija', 'Šola'),
('Kdo je odkril strukture atomov?', 'Ernest Rutherford', 'Niels Bohr', 'J.J. Thomson', 'Vse našteto', 'D', 11, 4, 'Kemija', 'Šola'),
('Kaj je oksidacija?', 'Pridobivanje elektronov', 'Izguba elektronov', 'Spajanje atomov', 'Cepitev molekul', 'B', 11, 4, 'Kemija', 'Šola'),
('Koliko je derivat sin(x)?', 'cos(x)', '-cos(x)', 'sin(x)', '-sin(x)', 'A', 11, 4, 'Matematika', 'Šola'),
('Kaj študija sociologija?', 'Posameznika', 'Družbo', 'Naravoslovje', 'Tehnologijo', 'B', 11, 3, 'Družboslovje', 'Šola'),
('Kdo je napisal "Na Sibirijo"?', 'Ivan Cankar', 'Josip Murn', 'Oton Župančič', 'Alojz Gradnik', 'C', 11, 4, 'Književnost', 'Šola'),
('Kaj je kinetična energija?', 'Energija položaja', 'Energija gibanja', 'Toplotna energija', 'Kemijska energija', 'B', 11, 3, 'Fizika', 'Šola'),
('Koliko je arcsin(1/2)?', 'π/6', 'π/4', 'π/3', 'π/2', 'A', 11, 4, 'Matematika', 'Šola');