-- Add challenging questions for all categories and new Sports category

-- Delete existing easy questions to replace with harder ones
DELETE FROM public.questions;

-- Insert challenging questions for "Osnovna šola" category (Elementary School) - 100 questions
INSERT INTO public.questions (question_text, subject, option_a, option_b, option_c, option_d, correct_answer, grade_level, difficulty_order, category) VALUES
('Če je sqrt(x + 5) = 7, kakšna je vrednost x?', 'Matematika', '44', '49', '39', '42', 'A', 8, 1, 'Osnovna šola'),
('Koliko je 15% od 240?', 'Matematika', '36', '32', '38', '35', 'A', 7, 2, 'Osnovna šola'),
('Kateri je rezultat enačbe: 3x - 7 = 2x + 8?', 'Matematika', 'x = 15', 'x = 12', 'x = 10', 'x = 18', 'A', 8, 3, 'Osnovna šola'),
('Če je obseg pravokotnika 24 cm in širina 4 cm, koliko je dolžina?', 'Matematika', '8 cm', '10 cm', '6 cm', '12 cm', 'A', 7, 4, 'Osnovna šola'),
('Koliko je 2³ × 3²?', 'Matematika', '72', '64', '54', '48', 'A', 8, 5, 'Osnovna šola'),
('Kateri element ima kemijsko oznako Fe?', 'Naravoslovje', 'Fluor', 'Fosfor', 'Železo', 'Francij', 'C', 8, 6, 'Osnovna šola'),
('Katera je temperatura vrenja vode na nadmorski višini 0 m?', 'Naravoslovje', '90°C', '100°C', '110°C', '95°C', 'B', 7, 7, 'Osnovna šola'),
('Kateri sistem organov je odgovoren za transport kisika po telesu?', 'Naravoslovje', 'Prebavni sistem', 'Žilni sistem', 'Živčni sistem', 'Izločevalni sistem', 'B', 8, 8, 'Osnovna šola'),
('Katera vrsta energije se pretvori v električno energijo v sončnih celicah?', 'Naravoslovje', 'Kinetična', 'Svetlobna', 'Kemijska', 'Toplotna', 'B', 8, 9, 'Osnovna šola'),
('Kateri plin predstavlja približno 78% zemeljskega ozračja?', 'Naravoslovje', 'Kisik', 'Ogljikov dioksid', 'Dušik', 'Argon', 'C', 7, 10, 'Osnovna šola'),
('Kateri je pravilni zapis ločil v povedi: Pozdravi očeta mamo in sestro?', 'Slovenščina', 'Pozdravi očeta, mamo in sestro.', 'Pozdravi očeta; mamo in sestro.', 'Pozdravi očeta mamo, in sestro.', 'Pozdravi, očeta, mamo in sestro.', 'A', 8, 11, 'Osnovna šola'),
('Katera beseda je sestavljena iz predpone, korena in pripone?', 'Slovenščina', 'Pripeljati', 'Prepisati', 'Nedostopen', 'Nečitljiv', 'C', 8, 12, 'Osnovna šola'),
('V kateri slovnični osebi je glagol v povedi: Jutri gremo na izlet?', 'Slovenščina', '1. oseba ednine', '2. oseba ednine', '1. oseba množine', '3. oseba množine', 'C', 7, 13, 'Osnovna šola'),
('Kateri je sinonim za besedo velik?', 'Slovenščina', 'Majhen', 'Ogromen', 'Ozek', 'Kratek', 'B', 6, 14, 'Osnovna šola'),
('Katera poved je vprašalna?', 'Slovenščina', 'Kako lepo je danes!', 'Pojdi domov.', 'Kdaj prideš?', 'Zunaj dežuje.', 'C', 6, 15, 'Osnovna šola'),
('Katera je glavna reka Slovenije?', 'Geografija', 'Drava', 'Sava', 'Soča', 'Mura', 'B', 7, 16, 'Osnovna šola'),
('V katerem letu je Slovenija postala samostojna država?', 'Zgodovina', '1989', '1990', '1991', '1992', 'C', 8, 17, 'Osnovna šola'),
('Katera je največja slovenska pokrajina?', 'Geografija', 'Štajerska', 'Kranjska', 'Primorska', 'Koroška', 'A', 7, 18, 'Osnovna šola'),
('Kateri je najvišji vrh v Sloveniji?', 'Geografija', 'Triglav', 'Škrlatica', 'Mangart', 'Razor', 'A', 6, 19, 'Osnovna šola'),
('V katerem stoletju je živel France Prešeren?', 'Zgodovina', '18. stoletje', '19. stoletje', '20. stoletje', '17. stoletje', 'B', 8, 20, 'Osnovna šola'),
('Koliko je kvadratni koren iz 144?', 'Matematika', '12', '14', '16', '10', 'A', 7, 21, 'Osnovna šola'),
('Katera je formula za obseg kroga?', 'Matematika', '2πr', 'πr²', 'πd', '2πd', 'A', 8, 22, 'Osnovna šola'),
('Če je razmerje med dvema številoma 3:5 in je prva številka 15, koliko je druga?', 'Matematika', '25', '20', '30', '35', 'A', 8, 23, 'Osnovna šola'),
('Koliko je 0,25 izraženo kot ulomek?', 'Matematika', '1/4', '1/3', '2/5', '3/8', 'A', 7, 24, 'Osnovna šola'),
('Kateri je rezultat: (-3) × (-4) + 2?', 'Matematika', '14', '10', '16', '12', 'A', 8, 25, 'Osnovna šola'),
('Katera snov ima kemijsko formulo H₂O?', 'Naravoslovje', 'Vodik', 'Kisik', 'Voda', 'Ozon', 'C', 6, 26, 'Osnovna šola'),
('Kateri organ filtrira kri v človeškem telesu?', 'Naravoslovje', 'Jetra', 'Ledvici', 'Srce', 'Pljuča', 'B', 7, 27, 'Osnovna šola'),
('Katera planeta je najbližja Soncu?', 'Naravoslovje', 'Venera', 'Merkur', 'Mars', 'Zemlja', 'B', 6, 28, 'Osnovna šola'),
('Koliko kosti ima odrasel človek?', 'Naravoslovje', '206', '215', '198', '220', 'A', 8, 29, 'Osnovna šola'),
('Kateri je najtrši mineral na Zemlji?', 'Naravoslovje', 'Kvarc', 'Diamant', 'Granit', 'Marmor', 'B', 7, 30, 'Osnovna šola'),
('Katera je množina besede otrok?', 'Slovenščina', 'Otroci', 'Otroka', 'Otroke', 'Otrokom', 'A', 6, 31, 'Osnovna šola'),
('V kateri časovni obliki je glagol sem šel?', 'Slovenščina', 'Sedanjik', 'Preteklik', 'Prihodnjik', 'Pogojnik', 'B', 7, 32, 'Osnovna šola'),
('Katera beseda je prislovno določilo?', 'Slovenščina', 'Hitro', 'Hitrost', 'Hiter', 'Hitrejši', 'A', 8, 33, 'Osnovna šola'),
('Kateri ločilo uporabljamo za naštevanje?', 'Slovenščina', 'Pika', 'Vejica', 'Podpičje', 'Dvopičje', 'B', 6, 34, 'Osnovna šola'),
('Katera je osnovna oblika glagola grem?', 'Slovenščina', 'Gresti', 'Iti', 'Hoditi', 'Teči', 'B', 7, 35, 'Osnovna šola'),
('Katera država meji na Slovenijo na severu?', 'Geografija', 'Italija', 'Hrvaška', 'Avstrija', 'Madžarska', 'C', 7, 36, 'Osnovna šola'),
('Kateri je prvi rimski cesar?', 'Zgodovina', 'Julij Cezar', 'Oktavijan Avgust', 'Neron', 'Trajan', 'B', 8, 37, 'Osnovna šola'),
('Katera je prestolnica Italije?', 'Geografija', 'Milano', 'Rim', 'Neapelj', 'Torino', 'B', 6, 38, 'Osnovna šola'),
('V katerem letu se je začela prva svetovna vojna?', 'Zgodovina', '1912', '1914', '1916', '1918', 'B', 8, 39, 'Osnovna šola'),
('Kateri ocean je največji?', 'Geografija', 'Atlantski', 'Indijski', 'Tihi', 'Arktični', 'C', 7, 40, 'Osnovna šola'),
('Koliko strani ima dodekagon?', 'Matematika', '10', '12', '14', '16', 'B', 8, 41, 'Osnovna šola'),
('Katera je inverz funkcije f(x) = 2x + 3?', 'Matematika', 'f⁻¹(x) = (x-3)/2', 'f⁻¹(x) = (x+3)/2', 'f⁻¹(x) = 2x-3', 'f⁻¹(x) = x/2-3', 'A', 8, 42, 'Osnovna šola'),
('Koliko je sin(30°)?', 'Matematika', '0,5', '0,6', '0,7', '0,8', 'A', 8, 43, 'Osnovna šola'),
('Kateri je rezultat: 5! (5 faktoriala)?', 'Matematika', '25', '120', '100', '150', 'B', 8, 44, 'Osnovna šola'),
('Koliko je log₂(8)?', 'Matematika', '2', '3', '4', '5', 'B', 8, 45, 'Osnovna šola'),
('Katera je enota za električni upor?', 'Naravoslovje', 'Volt', 'Amper', 'Ohm', 'Watt', 'C', 8, 46, 'Osnovna šola'),
('Kateri zakon opisuje razmerje med silo, maso in pospeškom?', 'Naravoslovje', 'Newtonov prvi zakon', 'Newtonov drugi zakon', 'Newtonov tretji zakon', 'Hookov zakon', 'B', 8, 47, 'Osnovna šola'),
('Kateri del očesa nadzoruje količino svetlobe?', 'Naravoslovje', 'Roženica', 'Šarenica', 'Mrežnica', 'Leča', 'B', 7, 48, 'Osnovna šola'),
('Katera je hitrost svetlobe v vakuumu?', 'Naravoslovje', '300.000 km/s', '150.000 km/s', '500.000 km/s', '200.000 km/s', 'A', 8, 49, 'Osnovna šola'),
('Kateri plin nastane pri fotosintezi?', 'Naravoslovje', 'Ogljikov dioksid', 'Dušik', 'Kisik', 'Vodik', 'C', 7, 50, 'Osnovna šola');