-- Insert geography questions from CSV data
INSERT INTO public.questions (question_text, category, subject, grade_level, difficulty_order, option_a, option_b, option_c, option_d, correct_answer) VALUES
('What is the capital of France?', 'Geografija', 'Geografija', 2, 1, 'Paris', 'Madrid', 'Rome', 'Berlin', 'A'),
('In which continent is France located?', 'Geografija', 'Geografija', 2, 1, 'North America', 'South America', 'Australia', 'Europe', 'D'),
('Which is the largest continent by land area?', 'Geografija', 'Geografija', 2, 1, 'Europe', 'North America', 'Asia', 'Africa', 'C'),
('Which is the largest ocean on Earth?', 'Geografija', 'Geografija', 2, 1, 'Arctic Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'B'),
('On which side of the Earth does the sun rise?', 'Geografija', 'Geografija', 2, 1, 'East', 'West', 'North', 'South', 'A'),
('Which imaginary line divides the Earth into the Northern and Southern Hemispheres?', 'Geografija', 'Geografija', 2, 1, 'Prime Meridian', 'Tropic of Cancer', 'Arctic Circle', 'Equator', 'D'),
('Which imaginary line is defined as 0 degrees longitude?', 'Geografija', 'Geografija', 2, 1, 'Tropic of Capricorn', 'Antarctic Circle', 'Prime Meridian', 'Equator', 'C'),
('Which country is commonly described as being shaped like a boot?', 'Geografija', 'Geografija', 3, 2, 'Portugal', 'Italy', 'Spain', 'Greece', 'B'),
('Which city lies on two continents (Europe and Asia)?', 'Geografija', 'Geografija', 3, 2, 'Istanbul', 'Athens', 'Moscow', 'Cairo', 'A'),
('Which river flows through London?', 'Geografija', 'Geografija', 3, 2, 'Volga', 'Mekong', 'Ganges', 'Thames', 'D'),
('Which sea lies between Italy and the Balkan Peninsula?', 'Geografija', 'Geografija', 3, 2, 'Aegean Sea', 'Ionian Sea', 'Adriatic Sea', 'Mediterranean Sea', 'C'),
('Which strait connects the Atlantic Ocean to the Mediterranean Sea?', 'Geografija', 'Geografija', 3, 2, 'Bering Strait', 'Strait of Gibraltar', 'Bosporus', 'Strait of Hormuz', 'B'),
('Which of the following countries is landlocked?', 'Geografija', 'Geografija', 3, 2, 'Austria', 'Spain', 'Japan', 'United Kingdom', 'A'),
('The Ural Mountains are commonly considered the natural boundary between which two continents?', 'Geografija', 'Geografija', 3, 2, 'Africa and Asia', 'North America and Asia', 'Europe and Africa', 'Europe and Asia', 'D'),
('In which mountain range is Mount Everest located?', 'Geografija', 'Geografija', 1, 3, 'Alps', 'Rocky Mountains', 'Himalayas', 'Andes', 'C'),
('Which is the highest mountain in Africa?', 'Geografija', 'Geografija', 1, 3, 'Mount Elgon', 'Kilimanjaro', 'Mount Kenya', 'Atlas Mountains', 'B'),
('Which is the highest mountain in North America?', 'Geografija', 'Geografija', 1, 3, 'Denali', 'Mount Logan', 'Mount Whitney', 'Mount Elbert', 'A'),
('Which lake is the deepest freshwater lake in the world?', 'Geografija', 'Geografija', 1, 3, 'Lake Superior', 'Lake Tanganyika', 'Lake Victoria', 'Lake Baikal', 'D'),
('Which is the largest hot desert in the world?', 'Geografija', 'Geografija', 1, 3, 'Kalahari', 'Mojave', 'Sahara', 'Gobi', 'C'),
('Which biome receives the most rainfall on average?', 'Geografija', 'Geografija', 1, 3, 'Taiga (boreal forest)', 'Tropical rainforest', 'Tundra', 'Desert', 'B'),
('Which climate is characterized by dry summers and mild, wet winters and is typical of the Mediterranean region?', 'Geografija', 'Geografija', 1, 3, 'Mediterranean', 'Tropical', 'Polar', 'Arid', 'A'),
('Which river is primarily in South America and is famous for its enormous discharge?', 'Geografija', 'Geografija', 2, 4, 'Nile', 'Yangtze', 'Mississippi', 'Amazon', 'D'),
('The Great Barrier Reef is located off the coast of which country?', 'Geografija', 'Geografija', 2, 4, 'India', 'South Africa', 'Australia', 'Brazil', 'C'),
('Which of these countries is crossed by the Equator?', 'Geografija', 'Geografija', 2, 4, 'Sweden', 'Ecuador', 'Italy', 'Poland', 'B'),
('Which U.S. state contains the Grand Canyon?', 'Geografija', 'Geografija', 2, 4, 'Arizona', 'Nevada', 'Utah', 'New Mexico', 'A'),
('What is the capital city of New Zealand?', 'Geografija', 'Geografija', 2, 4, 'Auckland', 'Christchurch', 'Hamilton', 'Wellington', 'D'),
('Which map scale shows the most detail (largest scale)?', 'Geografija', 'Geografija', 2, 4, '1:250,000', '1:1,000,000', '1:25,000', '1:100,000', 'C'),
('On a standard map oriented with north at the top, which cardinal direction is to the left?', 'Geografija', 'Geografija', 2, 4, 'South', 'West', 'East', 'North', 'B'),
('Which ocean lies off the west coast of California?', 'Geografija', 'Geografija', 3, 5, 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'A'),
('Which country has the largest land area in the world?', 'Geografija', 'Geografija', 3, 5, 'Canada', 'China', 'United States', 'Russia', 'D'),
('Which is the smallest independent country in the world by area?', 'Geografija', 'Geografija', 3, 5, 'San Marino', 'Liechtenstein', 'Vatican City', 'Monaco', 'C'),
('Which sea lies between the Arabian Peninsula and northeastern Africa?', 'Geografija', 'Geografija', 3, 5, 'Caribbean Sea', 'Red Sea', 'Black Sea', 'Baltic Sea', 'B'),
('Which country is well known for its fjords?', 'Geografija', 'Geografija', 3, 5, 'Norway', 'Greece', 'Egypt', 'Brazil', 'A'),
('Which river flows through Vienna, the capital of Austria?', 'Geografija', 'Geografija', 3, 5, 'Rhine', 'Thames', 'Volga', 'Danube', 'D'),
('Which of the following is an island nation?', 'Geografija', 'Geografija', 3, 5, 'Poland', 'Hungary', 'Japan', 'Germany', 'C'),
('Which of the following is a peninsula?', 'Geografija', 'Geografija', 3, 6, 'Andes', 'Iberian Peninsula', 'Sahara', 'Lake Baikal', 'B'),
('Which color appears on the national flag of France?', 'Geografija', 'Geografija', 3, 6, 'Blue', 'Green', 'Orange', 'Unknown', 'A'),
('Which country spans both Europe and Asia?', 'Geografija', 'Geografija', 3, 6, 'Brazil', 'Australia', 'Kenya', 'Turkey', 'D'),
('Which large lake is located in East Africa and is one of the African Great Lakes?', 'Geografija', 'Geografija', 3, 6, 'Lake Superior', 'Lake Ontario', 'Lake Victoria', 'Lake Baikal', 'C'),
('Which ocean meets the Atlantic Ocean near the Cape of Good Hope?', 'Geografija', 'Geografija', 3, 6, 'Southern Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean', 'B'),
('Which country is often called the ''Land of a Thousand Lakes''?', 'Geografija', 'Geografija', 3, 6, 'Finland', 'Switzerland', 'Nepal', 'Chile', 'A'),
('Which U.S. state is the smallest by land area?', 'Geografija', 'Geografija', 3, 6, 'Delaware', 'Connecticut', 'New Jersey', 'Rhode Island', 'D'),
('Which river forms much of the border between the United States and Mexico?', 'Geografija', 'Geografija', 4, 7, 'Colorado', 'Columbia', 'Rio Grande', 'Mississippi', 'C'),
('What is the capital city of Canada?', 'Geografija', 'Geografija', 4, 7, 'Montreal', 'Ottawa', 'Toronto', 'Vancouver', 'B'),
('Which sea is east of Italy and west of the Balkans?', 'Geografija', 'Geografija', 4, 7, 'Adriatic Sea', 'Aegean Sea', 'Tyrrhenian Sea', 'Ionian Sea', 'A'),
('Which strait divides the European and Asian parts of Turkey?', 'Geografija', 'Geografija', 4, 7, 'Strait of Gibraltar', 'Bering Strait', 'Strait of Hormuz', 'Bosporus', 'D'),
('Which body of water, sometimes called the world''s largest lake, is actually a saltwater basin and is landlocked?', 'Geografija', 'Geografija', 4, 7, 'Lake Baikal', 'Lake Victoria', 'Caspian Sea', 'Lake Superior', 'C'),
('What is the capital of Spain?', 'Geografija', 'Geografija', 4, 7, 'London', 'Madrid', 'Rome', 'Berlin', 'B'),
('In which continent is Spain located?', 'Geografija', 'Geografija', 4, 7, 'Europe', 'South America', 'Australia', 'Africa', 'A'),
('Which is the largest continent by land area? (1)', 'Geografija', 'Geografija', 5, 8, 'Africa', 'Europe', 'North America', 'Asia', 'D'),
('Which is the largest ocean on Earth? (1)', 'Geografija', 'Geografija', 5, 8, 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'C'),
('On which side of the Earth does the sun rise? (1)', 'Geografija', 'Geografija', 5, 8, 'South', 'East', 'West', 'North', 'B'),
('Which imaginary line divides the Earth into the Northern and Southern Hemispheres? (1)', 'Geografija', 'Geografija', 5, 8, 'Equator', 'Prime Meridian', 'Tropic of Cancer', 'Arctic Circle', 'A'),
('Which imaginary line is defined as 0 degrees longitude? (1)', 'Geografija', 'Geografija', 5, 8, 'Equator', 'Tropic of Capricorn', 'Antarctic Circle', 'Prime Meridian', 'D'),
('Which country is commonly described as being shaped like a boot? (1)', 'Geografija', 'Geografija', 5, 8, 'Greece', 'Portugal', 'Italy', 'Spain', 'C'),
('Which city lies on two continents (Europe and Asia)? (1)', 'Geografija', 'Geografija', 5, 8, 'Cairo', 'Istanbul', 'Athens', 'Moscow', 'B'),
('Which river flows through Paris?', 'Geografija', 'Geografija', 3, 9, 'Seine', 'Nile', 'Amazon', 'Yangtze', 'A'),
('Which sea lies between Italy and the Balkan Peninsula? (1)', 'Geografija', 'Geografija', 3, 9, 'Mediterranean Sea', 'Aegean Sea', 'Ionian Sea', 'Adriatic Sea', 'D'),
('Which strait connects the Atlantic Ocean to the Mediterranean Sea? (1)', 'Geografija', 'Geografija', 3, 9, 'Strait of Hormuz', 'Bering Strait', 'Strait of Gibraltar', 'Bosporus', 'C'),
('Which of the following countries is landlocked? (1)', 'Geografija', 'Geografija', 3, 9, 'United Kingdom', 'Austria', 'Spain', 'Japan', 'B'),
('The Ural Mountains are commonly considered the natural boundary between which two continents? (1)', 'Geografija', 'Geografija', 3, 9, 'Europe and Asia', 'Africa and Asia', 'North America and Asia', 'Europe and Africa', 'A'),
('In which mountain range is Mount Everest located? (1)', 'Geografija', 'Geografija', 3, 9, 'Andes', 'Alps', 'Rocky Mountains', 'Himalayas', 'D'),
('Which is the highest mountain in Africa? (1)', 'Geografija', 'Geografija', 3, 9, 'Atlas Mountains', 'Mount Elgon', 'Kilimanjaro', 'Mount Kenya', 'C'),
('Which is the highest mountain in North America? (1)', 'Geografija', 'Geografija', 4, 10, 'Mount Elbert', 'Denali', 'Mount Logan', 'Mount Whitney', 'B'),
('Which lake is the deepest freshwater lake in the world? (1)', 'Geografija', 'Geografija', 4, 10, 'Lake Baikal', 'Lake Superior', 'Lake Tanganyika', 'Lake Victoria', 'A'),
('Which is the largest hot desert in the world? (1)', 'Geografija', 'Geografija', 4, 10, 'Gobi', 'Kalahari', 'Mojave', 'Sahara', 'D'),
('Which biome receives the most rainfall on average? (1)', 'Geografija', 'Geografija', 4, 10, 'Desert', 'Taiga (boreal forest)', 'Tropical rainforest', 'Tundra', 'C'),
('Which climate is characterized by dry summers and mild, wet winters and is typical of the Mediterranean region? (1)', 'Geografija', 'Geografija', 4, 10, 'Arid', 'Mediterranean', 'Tropical', 'Polar', 'B'),
('Which river is primarily in South America and is famous for its enormous discharge? (1)', 'Geografija', 'Geografija', 4, 10, 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'A'),
('The Great Barrier Reef is located off the coast of which country? (1)', 'Geografija', 'Geografija', 4, 10, 'Brazil', 'India', 'South Africa', 'Australia', 'D'),
('Which of these countries is crossed by the Equator? (1)', 'Geografija', 'Geografija', 7, 11, 'Poland', 'Sweden', 'Ecuador', 'Italy', 'C'),
('Which U.S. state contains the Grand Canyon? (1)', 'Geografija', 'Geografija', 7, 11, 'New Mexico', 'Arizona', 'Nevada', 'Utah', 'B'),
('What is the capital city of New Zealand? (1)', 'Geografija', 'Geografija', 7, 11, 'Wellington', 'Auckland', 'Christchurch', 'Hamilton', 'A'),
('Which map scale shows the most detail (largest scale)? (1)', 'Geografija', 'Geografija', 7, 11, '1:100,000', '1:250,000', '1:1,000,000', '1:25,000', 'D'),
('On a standard map oriented with north at the top, which cardinal direction is to the left? (1)', 'Geografija', 'Geografija', 7, 11, 'North', 'South', 'West', 'East', 'C'),
('Which ocean lies off the west coast of California? (1)', 'Geografija', 'Geografija', 7, 11, 'Arctic Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'B'),
('Which country has the largest land area in the world? (1)', 'Geografija', 'Geografija', 7, 11, 'Russia', 'Canada', 'China', 'United States', 'A'),
('Which is the smallest independent country in the world by area? (1)', 'Geografija', 'Geografija', 5, 12, 'Monaco', 'San Marino', 'Liechtenstein', 'Vatican City', 'D'),
('Which sea lies between the Arabian Peninsula and northeastern Africa? (1)', 'Geografija', 'Geografija', 5, 12, 'Baltic Sea', 'Caribbean Sea', 'Red Sea', 'Black Sea', 'C'),
('Which country is well known for its fjords? (1)', 'Geografija', 'Geografija', 5, 12, 'Brazil', 'Norway', 'Greece', 'Egypt', 'B'),
('Which river flows through Vienna, the capital of Austria? (1)', 'Geografija', 'Geografija', 5, 12, 'Danube', 'Rhine', 'Thames', 'Volga', 'A'),
('Which of the following is an island nation? (1)', 'Geografija', 'Geografija', 5, 12, 'Germany', 'Poland', 'Hungary', 'Japan', 'D'),
('Which of the following is a peninsula? (1)', 'Geografija', 'Geografija', 5, 12, 'Lake Baikal', 'Andes', 'Iberian Peninsula', 'Sahara', 'C'),
('Which color appears on the national flag of Spain?', 'Geografija', 'Geografija', 5, 12, 'Orange', 'Red', 'Green', 'Blue', 'B'),
('Which country spans both Europe and Asia? (1)', 'Geografija', 'Geografija', 6, 13, 'Turkey', 'Brazil', 'Australia', 'Kenya', 'A'),
('Which large lake is located in East Africa and is one of the African Great Lakes? (1)', 'Geografija', 'Geografija', 6, 13, 'Lake Baikal', 'Lake Superior', 'Lake Ontario', 'Lake Victoria', 'D'),
('Which ocean meets the Atlantic Ocean near the Cape of Good Hope? (1)', 'Geografija', 'Geografija', 6, 13, 'Arctic Ocean', 'Southern Ocean', 'Indian Ocean', 'Pacific Ocean', 'C'),
('Which country is often called the ''Land of a Thousand Lakes''? (1)', 'Geografija', 'Geografija', 6, 13, 'Chile', 'Finland', 'Switzerland', 'Nepal', 'B'),
('Which U.S. state is the smallest by land area? (1)', 'Geografija', 'Geografija', 6, 13, 'Rhode Island', 'Delaware', 'Connecticut', 'New Jersey', 'A'),
('Which river forms much of the border between the United States and Mexico? (1)', 'Geografija', 'Geografija', 6, 13, 'Mississippi', 'Colorado', 'Columbia', 'Rio Grande', 'D'),
('What is the capital city of Canada? (1)', 'Geografija', 'Geografija', 6, 13, 'Vancouver', 'Montreal', 'Ottawa', 'Toronto', 'C'),
('Which sea is east of Italy and west of the Balkans? (1)', 'Geografija', 'Geografija', 7, 14, 'Ionian Sea', 'Adriatic Sea', 'Aegean Sea', 'Tyrrhenian Sea', 'B'),
('Which strait divides the European and Asian parts of Turkey? (1)', 'Geografija', 'Geografija', 7, 14, 'Bosporus', 'Strait of Gibraltar', 'Bering Strait', 'Strait of Hormuz', 'A'),
('Which body of water, sometimes called the world''s largest lake, is actually a saltwater basin and is landlocked? (1)', 'Geografija', 'Geografija', 7, 14, 'Lake Superior', 'Lake Baikal', 'Lake Victoria', 'Caspian Sea', 'D'),
('What is the capital of Italy?', 'Geografija', 'Geografija', 7, 14, 'London', 'Tokyo', 'Rome', 'Berlin', 'C'),
('In which continent is Italy located?', 'Geografija', 'Geografija', 7, 14, 'Antarctica', 'Europe', 'Australia', 'Africa', 'B'),
('Which is the largest continent by land area? (2)', 'Geografija', 'Geografija', 7, 14, 'Asia', 'Africa', 'Europe', 'North America', 'A'),
('Which is the largest ocean on Earth? (2)', 'Geografija', 'Geografija', 7, 14, 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 'D'),
('On which side of the Earth does the sun rise? (2)', 'Geografija', 'Geografija', 5, 15, 'North', 'South', 'East', 'West', 'C'),
('Which imaginary line divides the Earth into the Northern and Southern Hemispheres? (2)', 'Geografija', 'Geografija', 5, 15, 'Arctic Circle', 'Equator', 'Prime Meridian', 'Tropic of Cancer', 'B'),
('Which imaginary line is defined as 0 degrees longitude? (2)', 'Geografija', 'Geografija', 5, 15, 'Prime Meridian', 'Equator', 'Tropic of Capricorn', 'Antarctic Circle', 'A'),
('Which country is commonly described as being shaped like a boot? (2)', 'Geografija', 'Geografija', 5, 15, 'Spain', 'Greece', 'Portugal', 'Italy', 'D'),
('Which city lies on two continents (Europe and Asia)? (2)', 'Geografija', 'Geografija', 5, 15, 'Moscow', 'Cairo', 'Istanbul', 'Athens', 'C'),
('Which river flows through Tokyo?', 'Geografija', 'Geografija', 5, 15, 'Mississippi', 'Sumida', 'Amazon', 'Yangtze', 'B'),
('Which sea lies between Italy and the Balkan Peninsula? (2)', 'Geografija', 'Geografija', 5, 15, 'Adriatic Sea', 'Mediterranean Sea', 'Aegean Sea', 'Ionian Sea', 'A'),
('Which strait connects the Atlantic Ocean to the Mediterranean Sea? (2)', 'Geografija', 'Geografija', 8, 16, 'Bosporus', 'Strait of Hormuz', 'Bering Strait', 'Strait of Gibraltar', 'D'),
('Which of the following countries is landlocked? (2)', 'Geografija', 'Geografija', 8, 16, 'Japan', 'United Kingdom', 'Austria', 'Spain', 'C'),
('The Ural Mountains are commonly considered the natural boundary between which two continents? (2)', 'Geografija', 'Geografija', 8, 16, 'Europe and Africa', 'Europe and Asia', 'Africa and Asia', 'North America and Asia', 'B'),
('In which mountain range is Mount Everest located? (2)', 'Geografija', 'Geografija', 8, 16, 'Himalayas', 'Andes', 'Alps', 'Rocky Mountains', 'A'),
('Which is the highest mountain in Africa? (2)', 'Geografija', 'Geografija', 8, 16, 'Mount Kenya', 'Atlas Mountains', 'Mount Elgon', 'Kilimanjaro', 'D'),
('Which is the highest mountain in North America? (2)', 'Geografija', 'Geografija', 8, 16, 'Mount Whitney', 'Mount Elbert', 'Denali', 'Mount Logan', 'C'),
('Which lake is the deepest freshwater lake in the world? (2)', 'Geografija', 'Geografija', 8, 16, 'Lake Victoria', 'Lake Baikal', 'Lake Superior', 'Lake Tanganyika', 'B'),
('Which is the largest hot desert in the world? (2)', 'Geografija', 'Geografija', 9, 17, 'Sahara', 'Gobi', 'Kalahari', 'Mojave', 'A'),
('Which biome receives the most rainfall on average? (2)', 'Geografija', 'Geografija', 9, 17, 'Tundra', 'Desert', 'Taiga (boreal forest)', 'Tropical rainforest', 'D'),
('Which climate is characterized by dry summers and mild, wet winters and is typical of the Mediterranean region? (2)', 'Geografija', 'Geografija', 9, 17, 'Polar', 'Arid', 'Mediterranean', 'Tropical', 'C'),
('Which river is primarily in South America and is famous for its enormous discharge? (2)', 'Geografija', 'Geografija', 9, 17, 'Mississippi', 'Amazon', 'Nile', 'Yangtze', 'B'),
('The Great Barrier Reef is located off the coast of which country? (2)', 'Geografija', 'Geografija', 9, 17, 'Australia', 'Brazil', 'India', 'South Africa', 'A'),
('Which of these countries is crossed by the Equator? (2)', 'Geografija', 'Geografija', 9, 17, 'Italy', 'Poland', 'Sweden', 'Ecuador', 'D'),
('Which U.S. state contains the Grand Canyon? (2)', 'Geografija', 'Geografija', 9, 17, 'Utah', 'New Mexico', 'Arizona', 'Nevada', 'C'),
('What is the capital city of New Zealand? (2)', 'Geografija', 'Geografija', 7, 18, 'Hamilton', 'Wellington', 'Auckland', 'Christchurch', 'B'),
('Which map scale shows the most detail (largest scale)? (2)', 'Geografija', 'Geografija', 7, 18, '1:25,000', '1:100,000', '1:250,000', '1:1,000,000', 'A'),
('On a standard map oriented with north at the top, which cardinal direction is to the left? (2)', 'Geografija', 'Geografija', 7, 18, 'East', 'North', 'South', 'West', 'D'),
('Which ocean lies off the west coast of California? (2)', 'Geografija', 'Geografija', 7, 18, 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'C'),
('Which country has the largest land area in the world? (2)', 'Geografija', 'Geografija', 7, 18, 'United States', 'Russia', 'Canada', 'China', 'B'),
('Which is the smallest independent country in the world by area? (2)', 'Geografija', 'Geografija', 7, 18, 'Vatican City', 'Monaco', 'San Marino', 'Liechtenstein', 'A'),
('Which sea lies between the Arabian Peninsula and northeastern Africa? (2)', 'Geografija', 'Geografija', 7, 18, 'Black Sea', 'Baltic Sea', 'Caribbean Sea', 'Red Sea', 'D'),
('Which country is well known for its fjords? (2)', 'Geografija', 'Geografija', 8, 19, 'Egypt', 'Brazil', 'Norway', 'Greece', 'C'),
('Which river flows through Vienna, the capital of Austria? (2)', 'Geografija', 'Geografija', 8, 19, 'Volga', 'Danube', 'Rhine', 'Thames', 'B'),
('Which of the following is an island nation? (2)', 'Geografija', 'Geografija', 8, 19, 'Japan', 'Germany', 'Poland', 'Hungary', 'A'),
('Which of the following is a peninsula? (2)', 'Geografija', 'Geografija', 8, 19, 'Sahara', 'Lake Baikal', 'Andes', 'Iberian Peninsula', 'D'),
('Which color appears on the national flag of Italy?', 'Geografija', 'Geografija', 8, 19, 'Orange', 'Unknown', 'Green', 'Blue', 'C'),
('Which country spans both Europe and Asia? (2)', 'Geografija', 'Geografija', 8, 19, 'Kenya', 'Turkey', 'Brazil', 'Australia', 'B'),
('Which large lake is located in East Africa and is one of the African Great Lakes? (2)', 'Geografija', 'Geografija', 8, 19, 'Lake Victoria', 'Lake Baikal', 'Lake Superior', 'Lake Ontario', 'A'),
('Which ocean meets the Atlantic Ocean near the Cape of Good Hope? (2)', 'Geografija', 'Geografija', 9, 20, 'Pacific Ocean', 'Arctic Ocean', 'Southern Ocean', 'Indian Ocean', 'D'),
('Which country is often called the ''Land of a Thousand Lakes''? (2)', 'Geografija', 'Geografija', 9, 20, 'Nepal', 'Chile', 'Finland', 'Switzerland', 'C'),
('Which U.S. state is the smallest by land area? (2)', 'Geografija', 'Geografija', 9, 20, 'New Jersey', 'Rhode Island', 'Delaware', 'Connecticut', 'B'),
('Which river forms much of the border between the United States and Mexico? (2)', 'Geografija', 'Geografija', 9, 20, 'Rio Grande', 'Mississippi', 'Colorado', 'Columbia', 'A'),
('What is the capital city of Canada? (2)', 'Geografija', 'Geografija', 9, 20, 'Toronto', 'Vancouver', 'Montreal', 'Ottawa', 'D'),
('Which sea is east of Italy and west of the Balkans? (2)', 'Geografija', 'Geografija', 9, 20, 'Tyrrhenian Sea', 'Ionian Sea', 'Adriatic Sea', 'Aegean Sea', 'C'),
('Which strait divides the European and Asian parts of Turkey? (2)', 'Geografija', 'Geografija', 9, 20, 'Strait of Hormuz', 'Bosporus', 'Strait of Gibraltar', 'Bering Strait', 'B'),
('Which body of water, sometimes called the world''s largest lake, is actually a saltwater basin and is landlocked? (2)', 'Geografija', 'Geografija', 9, 21, 'Caspian Sea', 'Lake Superior', 'Lake Baikal', 'Lake Victoria', 'A'),
('What is the capital of Germany?', 'Geografija', 'Geografija', 9, 21, 'London', 'Tokyo', 'Ottawa', 'Berlin', 'D'),
('In which continent is Germany located?', 'Geografija', 'Geografija', 9, 21, 'Antarctica', 'Asia', 'Europe', 'Africa', 'C'),
('Which is the largest continent by land area? (3)', 'Geografija', 'Geografija', 9, 21, 'North America', 'Asia', 'Africa', 'Europe', 'B'),
('Which is the largest ocean on Earth? (3)', 'Geografija', 'Geografija', 9, 21, 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'A'),
('On which side of the Earth does the sun rise? (3)', 'Geografija', 'Geografija', 9, 21, 'West', 'North', 'South', 'East', 'D'),
('Which imaginary line divides the Earth into the Northern and Southern Hemispheres? (3)', 'Geografija', 'Geografija', 10, 22, 'Tropic of Cancer', 'Arctic Circle', 'Equator', 'Prime Meridian', 'C'),
('Which imaginary line is defined as 0 degrees longitude? (3)', 'Geografija', 'Geografija', 10, 22, 'Antarctic Circle', 'Prime Meridian', 'Equator', 'Tropic of Capricorn', 'B'),
('Which country is commonly described as being shaped like a boot? (3)', 'Geografija', 'Geografija', 10, 22, 'Italy', 'Spain', 'Greece', 'Portugal', 'A'),
('Which city lies on two continents (Europe and Asia)? (3)', 'Geografija', 'Geografija', 10, 22, 'Athens', 'Moscow', 'Cairo', 'Istanbul', 'D'),
('Which river flows through New York?', 'Geografija', 'Geografija', 10, 22, 'Mississippi', 'Danube', 'Hudson', 'Yangtze', 'C'),
('Which sea lies between Italy and the Balkan Peninsula? (3)', 'Geografija', 'Geografija', 10, 22, 'Ionian Sea', 'Adriatic Sea', 'Mediterranean Sea', 'Aegean Sea', 'B'),
('Which strait connects the Atlantic Ocean to the Mediterranean Sea? (3)', 'Geografija', 'Geografija', 11, 23, 'Strait of Gibraltar', 'Bosporus', 'Strait of Hormuz', 'Bering Strait', 'A'),
('Which of the following countries is landlocked? (3)', 'Geografija', 'Geografija', 11, 23, 'Spain', 'Japan', 'United Kingdom', 'Austria', 'D'),
('The Ural Mountains are commonly considered the natural boundary between which two continents? (3)', 'Geografija', 'Geografija', 11, 23, 'North America and Asia', 'Europe and Africa', 'Europe and Asia', 'Africa and Asia', 'C'),
('In which mountain range is Mount Everest located? (3)', 'Geografija', 'Geografija', 11, 23, 'Rocky Mountains', 'Himalayas', 'Andes', 'Alps', 'B'),
('Which is the highest mountain in Africa? (3)', 'Geografija', 'Geografija', 11, 23, 'Kilimanjaro', 'Mount Kenya', 'Atlas Mountains', 'Mount Elgon', 'A'),
('Which is the highest mountain in North America? (3)', 'Geografija', 'Geografija', 11, 23, 'Mount Logan', 'Mount Whitney', 'Mount Elbert', 'Denali', 'D'),
('Which lake is the deepest freshwater lake in the world? (3)', 'Geografija', 'Geografija', 9, 24, 'Lake Tanganyika', 'Lake Victoria', 'Lake Baikal', 'Lake Superior', 'C'),
('Which is the largest hot desert in the world? (3)', 'Geografija', 'Geografija', 9, 24, 'Mojave', 'Sahara', 'Gobi', 'Kalahari', 'B'),
('Which biome receives the most rainfall on average? (3)', 'Geografija', 'Geografija', 9, 24, 'Tropical rainforest', 'Tundra', 'Desert', 'Taiga (boreal forest)', 'A'),
('Which climate is characterized by dry summers and mild, wet winters and is typical of the Mediterranean region? (3)', 'Geografija', 'Geografija', 9, 24, 'Tropical', 'Polar', 'Arid', 'Mediterranean', 'D'),
('Which river is primarily in South America and is famous for its enormous discharge? (3)', 'Geografija', 'Geografija', 9, 24, 'Yangtze', 'Mississippi', 'Amazon', 'Nile', 'C'),
('The Great Barrier Reef is located off the coast of which country? (3)', 'Geografija', 'Geografija', 9, 24, 'South Africa', 'Australia', 'Brazil', 'India', 'B'),
('Which of these countries is crossed by the Equator? (3)', 'Geografija', 'Geografija', 10, 25, 'Ecuador', 'Italy', 'Poland', 'Sweden', 'A'),
('Which U.S. state contains the Grand Canyon? (3)', 'Geografija', 'Geografija', 10, 25, 'Nevada', 'Utah', 'New Mexico', 'Arizona', 'D'),
('What is the capital city of New Zealand? (3)', 'Geografija', 'Geografija', 10, 25, 'Christchurch', 'Hamilton', 'Wellington', 'Auckland', 'C'),
('Which map scale shows the most detail (largest scale)? (3)', 'Geografija', 'Geografija', 10, 25, '1:1,000,000', '1:25,000', '1:100,000', '1:250,000', 'B'),
('On a standard map oriented with north at the top, which cardinal direction is to the left? (3)', 'Geografija', 'Geografija', 10, 25, 'West', 'East', 'North', 'South', 'A'),
('Which ocean lies off the west coast of California? (3)', 'Geografija', 'Geografija', 10, 25, 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 'D'),
('Which country has the largest land area in the world? (3)', 'Geografija', 'Geografija', 11, 26, 'China', 'United States', 'Russia', 'Canada', 'C'),
('Which is the smallest independent country in the world by area? (3)', 'Geografija', 'Geografija', 11, 26, 'Liechtenstein', 'Vatican City', 'Monaco', 'San Marino', 'B'),
('Which sea lies between the Arabian Peninsula and northeastern Africa? (3)', 'Geografija', 'Geografija', 11, 26, 'Red Sea', 'Black Sea', 'Baltic Sea', 'Caribbean Sea', 'A'),
('Which country is well known for its fjords? (3)', 'Geografija', 'Geografija', 11, 26, 'Greece', 'Egypt', 'Brazil', 'Norway', 'D'),
('Which river flows through Vienna, the capital of Austria? (3)', 'Geografija', 'Geografija', 11, 26, 'Thames', 'Volga', 'Danube', 'Rhine', 'C'),
('Which of the following is an island nation? (3)', 'Geografija', 'Geografija', 11, 26, 'Hungary', 'Japan', 'Germany', 'Poland', 'B'),
('Which of the following is a peninsula? (3)', 'Geografija', 'Geografija', 12, 27, 'Iberian Peninsula', 'Sahara', 'Lake Baikal', 'Andes', 'A'),
('Which color appears on the national flag of Germany?', 'Geografija', 'Geografija', 12, 27, 'Green', 'Blue', 'Orange', 'Black', 'D'),
('Which country spans both Europe and Asia? (3)', 'Geografija', 'Geografija', 12, 27, 'Australia', 'Kenya', 'Turkey', 'Brazil', 'C'),
('Which large lake is located in East Africa and is one of the African Great Lakes? (3)', 'Geografija', 'Geografija', 12, 27, 'Lake Ontario', 'Lake Victoria', 'Lake Baikal', 'Lake Superior', 'B'),
('Which ocean meets the Atlantic Ocean near the Cape of Good Hope? (3)', 'Geografija', 'Geografija', 12, 27, 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean', 'Southern Ocean', 'A'),
('Which country is often called the ''Land of a Thousand Lakes''? (3)', 'Geografija', 'Geografija', 12, 27, 'Switzerland', 'Nepal', 'Chile', 'Finland', 'D'),
('Which U.S. state is the smallest by land area? (3)', 'Geografija', 'Geografija', 11, 28, 'Connecticut', 'New Jersey', 'Rhode Island', 'Delaware', 'C'),
('Which river forms much of the border between the United States and Mexico? (3)', 'Geografija', 'Geografija', 11, 28, 'Columbia', 'Rio Grande', 'Mississippi', 'Colorado', 'B'),
('What is the capital city of Canada? (3)', 'Geografija', 'Geografija', 11, 28, 'Ottawa', 'Toronto', 'Vancouver', 'Montreal', 'A'),
('Which sea is east of Italy and west of the Balkans? (3)', 'Geografija', 'Geografija', 11, 28, 'Aegean Sea', 'Tyrrhenian Sea', 'Ionian Sea', 'Adriatic Sea', 'D'),
('Which strait divides the European and Asian parts of Turkey? (3)', 'Geografija', 'Geografija', 11, 28, 'Bering Strait', 'Strait of Hormuz', 'Bosporus', 'Strait of Gibraltar', 'C'),
('Which body of water, sometimes called the world''s largest lake, is actually a saltwater basin and is landlocked? (3)', 'Geografija', 'Geografija', 11, 28, 'Lake Victoria', 'Caspian Sea', 'Lake Superior', 'Lake Baikal', 'B'),
('What is the capital of United Kingdom?', 'Geografija', 'Geografija', 12, 29, 'London', 'Tokyo', 'Ottawa', 'Canberra', 'A'),
('In which continent is United Kingdom located?', 'Geografija', 'Geografija', 12, 29, 'Africa', 'Antarctica', 'Asia', 'Europe', 'D'),
('Which is the largest continent by land area? (4)', 'Geografija', 'Geografija', 12, 29, 'Europe', 'North America', 'Asia', 'Africa', 'C'),
('Which is the largest ocean on Earth? (4)', 'Geografija', 'Geografija', 12, 29, 'Arctic Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'B'),
('On which side of the Earth does the sun rise? (4)', 'Geografija', 'Geografija', 12, 29, 'East', 'West', 'North', 'South', 'A'),
('Which imaginary line divides the Earth into the Northern and Southern Hemispheres? (4)', 'Geografija', 'Geografija', 12, 29, 'Prime Meridian', 'Tropic of Cancer', 'Arctic Circle', 'Equator', 'D'),
('Which imaginary line is defined as 0 degrees longitude? (4)', 'Geografija', 'Geografija', 11, 30, 'Tropic of Capricorn', 'Antarctic Circle', 'Prime Meridian', 'Equator', 'C'),
('Which country is commonly described as being shaped like a boot? (4)', 'Geografija', 'Geografija', 11, 30, 'Portugal', 'Italy', 'Spain', 'Greece', 'B'),
('Which city lies on two continents (Europe and Asia)? (4)', 'Geografija', 'Geografija', 11, 30, 'Istanbul', 'Athens', 'Moscow', 'Cairo', 'A'),
('Which river flows through Sydney?', 'Geografija', 'Geografija', 11, 30, 'Mississippi', 'Danube', 'Rhine', 'Parramatta', 'D'),
('Which sea lies between Italy and the Balkan Peninsula? (4)', 'Geografija', 'Geografija', 11, 30, 'Aegean Sea', 'Ionian Sea', 'Adriatic Sea', 'Mediterranean Sea', 'C'),
('Which strait connects the Atlantic Ocean to the Mediterranean Sea? (4)', 'Geografija', 'Geografija', 11, 30, 'Bering Strait', 'Strait of Gibraltar', 'Bosporus', 'Strait of Hormuz', 'B');