// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktisddcvdkklpsncwuwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0aXNkZGN2ZGtrbHBzbmN3dXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDMxMjQsImV4cCI6MjA2ODkxOTEyNH0.j1oi3x7PfW2qv47PkBa_Dk1bLCD-6clMKbX5BBt8New";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});